"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from datetime import timedelta
import environ
import cloudinary
from .sentry_config import init_sentry

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Determine which environment file to use based on DJANGO_ENV
# Set DJANGO_ENV=production to use production settings
# e.g., export DJANGO_ENV=production (Linux/Mac) or set DJANGO_ENV=production (Windows)
DJANGO_ENV = os.environ.get('DJANGO_ENV', 'development')
env_file = f'.env.{DJANGO_ENV}'

# Load environment variables from the appropriate .env file
env = environ.Env()
env_path = os.path.join(BASE_DIR, env_file)

if os.path.exists(env_path):
    print(f"Loading environment from {env_file}")
    environ.Env.read_env(env_path)
else:
    print(f"Warning: {env_file} not found, looking for .env file")
    # Fallback to .env if the specific environment file doesn't exist
    environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# Initialize Sentry with configuration from environment variables
init_sentry()
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('DEBUG', default=False)

ALLOWED_HOSTS = [
    '127.0.0.1',          # Allow access via 127.0.0.1
    'localhost',          # Allow access via localhost
    'backend',            # Allow access via backend service name in Docker
    "https://amarhealth.tech",
    "https://www.amarhealth.tech",
    "http://amarhealth.tech",
    "http://www.amarhealth.tech",
    "https://web-wizards-backend.whitepebble-a989e7cd.southeastasia.azurecontainerapps.io",
    "web-wizards-backend.whitepebble-a989e7cd.southeastasia.azurecontainerapps.io"
]

CSRF_TRUSTED_ORIGINS = [
    "https://web-wizards-backend.whitepebble-a989e7cd.southeastasia.azurecontainerapps.io",
]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",  # Vite development server
    "http://127.0.0.1:5173",
    "http://localhost:3000",  # React development server
    "http://127.0.0.1:3000",
    "https://amarhealth.tech",
    "https://www.amarhealth.tech",
    "http://amarhealth.tech",
    "http://www.amarhealth.tech",
    "https://web-wizards-backend.whitepebble-a989e7cd.southeastasia.azurecontainerapps.io",

]

# Allow credentials in CORS requests
CORS_ALLOW_CREDENTIALS = True

AUTH_USER_MODEL = 'users.Users'
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'cloudinary_storage',
    'django.contrib.staticfiles',
    'cloudinary',
    'rest_framework',
    'rest_framework.authtoken',  # Add this line for token authentication
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'django_filters',  # Add django-filters app
    'api',
    'apps.users',
    'apps.medical_records',  # Add medical_records app
    'apps.clinicians',       # Add clinicians app
    'apps.medications',      # Add medications app
    'apps.appointments',     # Add appointments app
    'apps.visualizations',   # Add visualizations app
    'apps.news',             # News app with correct path
    # OAuth related
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'dj_rest_auth',
    'dj_rest_auth.registration',  # Add this for registration endpoints
    'oauth2_provider',
    'social_django',
]

# Site ID required by allauth
SITE_ID = 1

# Authentication backends
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
    'social_core.backends.google.GoogleOAuth2',
]

# Google OAuth2 settings
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APP': {
            'client_id': env('GOOGLE_CLIENT_ID', default=''),
            'secret': env('GOOGLE_CLIENT_SECRET', default=''),
            'key': ''
        },
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        }
    }
}

# AllAuth settings
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_AUTHENTICATION_METHOD = 'email'


MIDDLEWARE = [
    'core.middleware.RateLimitMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Add whitenoise middleware
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': env('DATABASE_ENGINE'),
        'NAME': env('DATABASE_NAME'),
        'USER': env('DATABASE_USER'),
        'PASSWORD': env('DATABASE_PASSWORD'),
        'HOST': env('DATABASE_HOST'),
        'PORT': env('DATABASE_PORT'),
        'OPTIONS': {
            'ssl_mode': env('MYSQL_SSL_MODE', default='REQUIRED'),
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# WhiteNoise configuration
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# OCR Service settings
OCR_SERVICE_URL = env('OCR_SERVICE_URL', default='http://ocr_service:8000')

# OpenAI API Configuration
OPENAI_API_KEY = env('OPENAI_API_KEY', default='')

# Redis Cache Configuration - Disabled temporarily to fix connection error
# REDIS_URL = os.getenv('REDIS_URL', 'redis://redis:6379/1')
REDIS_URL = None  # Setting to None to disable Redis

# Update cache to use local memory instead of Redis
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "unique-snowflake",
    }
}

# Use database for session storage since Redis is disabled
SESSION_ENGINE = "django.contrib.sessions.backends.db"

# Cache timeout settings (in seconds)
CACHE_TTL = 60 * 15  # 15 minutes default


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    # Add cache control to REST Framework
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle'
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '1000/day',
        'user': '10000/day'
    }
}


# Simple JWT Settings
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),   # Changed back to 15 minutes
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),      # Increased refresh token lifetime
    'ROTATE_REFRESH_TOKENS': True,                    # Allow rotating refresh tokens
    'BLACKLIST_AFTER_ROTATION': True,                 # Blacklist old refresh tokens after rotation
    'UPDATE_LAST_LOGIN': True,                        # Update last login timestamp
    'ALGORITHM': 'HS256',                             # Algorithm for encoding/decoding JWT tokens
    'SIGNING_KEY': SECRET_KEY,                        # Signing key used for token encryption
    'AUTH_HEADER_TYPES': ('Bearer',),                 # Default prefix for the Authorization header
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
}


CLOUDINARY_STORAGE = {
    'CLOUD_NAME': env('CLOUDINARY_CLOUD_NAME'),
    'API_KEY': env('CLOUDINARY_API_KEY'),
    'API_SECRET': env('CLOUDINARY_API_SECRET'),
}

DEFAULT_FILE_STORAGE = "cloudinary_storage.storage.MediaCloudinaryStorage"

# Celery Configuration - Disabled temporarily
# CELERY_BROKER_URL = os.getenv('REDIS_URL', 'redis://localhost:6379/0')
# CELERY_RESULT_BACKEND = os.getenv('REDIS_URL', 'redis://localhost:6379/0')
CELERY_TASK_ALWAYS_EAGER = True  # Run tasks synchronously for testing
CELERY_BROKER_URL = None
CELERY_RESULT_BACKEND = None
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE

# Email Configuration - Always use SMTP backend for development and production
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'Ibn Sina <noreply@ibnsina.com>')

# Frontend URL for email verification and password reset links
FRONTEND_URL = os.environ.get('FRONTEND_URL', 'http://localhost:5173')

